print('Informe quatro notas.')
a = float(input('Informe a primeira nota:'))
b = float(input('Informe a segunda nota:'))
c = float(input('Informe a terceira nota:'))
d = float(input('Informe a quarta e última nota:'))
print(f'\nA média das notas informadas é {(a + b + c + d)/4}')
